name: le-fil-rouge
favicon: null
layout_spectrum: 0.63148
typography_spectrum: 0.76234
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: le fil rouge
description: 'C''est un fil, il est rouge.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FEFFFF'
    - '#BD0E13'
    - '#2D2118'
    - '#78572B'
    - '#F8C780'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
