typography_spectrum: 0.2574468
color:
  brandStrength: 0.3340425
  lightness: 1
  saturation: 0.8212766
  rhythmicContrast: 1
  brandColors:
    - '#FEFFFF'
    - '#BD0E13'
    - '#2D2118'
    - '#78572B'
    - '#F8C780'
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9191489
analytics:
  facebook: null
  google: null
  twitter: null
name: le-fil-rouge
cta:
  domain: null
  version: null
  bucket: null
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: le fil rouge
description: 'C''est un fil, il est rouge.'
purpose: []
