name: le-fil-rouge
favicon: null
layout_spectrum: 0.5633444890845567
typography_spectrum: 0.02785675204358995
title: le fil rouge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.010616187937557697
  lightness: 0.7903528064489365
  saturation: 0.9632168395910412
  rhythmicContrast: 0.9760460387915373
purpose: []
